; Fichier de définition d'un carillon pour son utilisation par l'application Midillon
;
; les charactères espace et les lignes vides sont ignorés
; une ligne de commentaire commence par le caractère ;
; les notes peuvent être indiquées de la façon suivante (insensible à la casse) : 
;    do, ré, mi, fa, sol, la, si (ou A à G) suivi de # ou b suivi du numéro d'octave de 0 à 9
;    par exemple : do5, sol#3, sib4, Sib4, d5, G#3

; cette notation des notes peut être utilisée également pour les fichier .wav d'échantillons sonores donnés à Midillon

; nom du carillon
Nom = Carillon Bollée de Châtellerault

; valeur de transposition en demi-tons du clavier vers les cloches
Transposition clavier = +7

; définition des touches du clavier 
Clavier première touche = Do3
Clavier dernière touche = Mi7
Clavier touches manquantes = Do#3 Ré#7
Clavier touches inactives = Fa#3 Ré7 Mi7
; "touches inactives" = touches présentes mais non connectées à une cloche

; définition des touches du pédalier
Pédalier première touche = Fa2
Pédalier dernière touche = La4
Pédalier touches manquantes = Fa#2 Sol#2 Si2 Do#3
Pédalier touches inactives = Fa#3

; ----------------------------------------------
; définition du jeu automatique
; nombre de repères par tour du cadran à noter ou autre système de repérage de déplacement du jeu automatique
Nombre de repères = 88

; temps de révolution du système de repérage (en millisecondes)
Temps de révolution = 3100

; définition des leviers actionneurs : <numéro du levier> <note de la cloche jouée par la levier>
Levier =   1  do3
Levier =   2  ré3
Levier =   3  mi3
Levier =   4  fa3
Levier =   5  sol3
Levier =   6  la3
Levier =   7  la#3
Levier =   8  la#3
Levier =   9  si3
Levier =  10  si3
Levier =  11  si3
Levier =  12  do4
Levier =  13  do4
Levier =  14  do4
Levier =  15  ré4
Levier =  16  ré4
Levier =  17  ré4
Levier =  18  ré#4
Levier =  19  ré#4
Levier =  20  mi4
Levier =  21  
Levier =  22  mi4
Levier =  23  mi4
Levier =  24  fa4
Levier =  25  fa4
Levier =  26  fa4
Levier =  27  fa#4
Levier =  28  fa#4
Levier =  29  sol4
Levier =  30  sol4
Levier =  31  sol4
Levier =  32  sol#4
Levier =  33  sol#4
Levier =  34  la4
Levier =  35  la4
Levier =  36  la4
Levier =  37  la#4
Levier =  38  la#4
Levier =  39  si4
Levier =  40  si4
Levier =  41  si4
Levier =  42  do5
Levier =  43  do5
Levier =  44  do5
Levier =  45  do#5
Levier =  46  do#5
Levier =  47  ré5
Levier =  48  ré5
Levier =  49  ré5
Levier =  50  ré#5
Levier =  51  ré#5
Levier =  52  mi5
Levier =  53  mi5
Levier =  54  fa5
Levier =  55  fa5
Levier =  56  fa5
Levier =  57  fa#5
Levier =  58  fa#5
Levier =  59  sol5
Levier =  60  sol5
Levier =  61  sol5
Levier =  62  sol#5
Levier =  63  
Levier =  64  la5
Levier =  65  la5
Levier =  66  la5
Levier =  67  la#5
Levier =  68  la#5
Levier =  69  si5
Levier =  70  si5
Levier =  71  do6
Levier =  72  do6
Levier =  73  do#6
Levier =  74  ré6
Levier =  75  ré6
Levier =  76  ré#6
Levier =  77  ré#6
Levier =  78  mi6
Levier =  79  mi6
Levier =  80  fa6
Levier =  81  fa6
Levier =  82  fa#6
Levier =  83  fa#6
Levier =  84  sol6
Levier =  85  sol6
Levier =  86  sol#6
Levier =  87  la6
Levier =  88  la6
Levier =  89  la#6
Levier =  90  si6
Levier =  91  si6
Levier =  92  do7
Levier =  93  do7
Levier =  94  do#7
Levier =  95  do#7
Levier =  96  ré7
Levier =  97  ré#7
Levier =  98  mi7
Levier =  99  fa7
Levier = 100  fa#7
Levier = 101  sol7
Levier = 102  sol#7
